version: '2'

services:
  sut:
    build: .
    command: pieni
    volumes:
      - ./src:/root/
    working_dir: /root
    environment:
      PIENI_PORT: 3000

  pieni-test:
    container_name: pieni-test
    build:
      context: .
      dockerfile: Dockerfile-test
    working_dir: /root
    command: "./benchmark.sh http://sut:3000"
