version: '2'

services:
  pieni:
    container_name: pieni
    build: .
    command: pieni
    volumes:
      - ./src:/root/
    working_dir: /root
    environment:
      PIENI_PORT: 3000

  sut:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - pieni
    working_dir: /root
    command: "./benchmark.sh http://pieni:3000"
